### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by motin** [ManNguyen/LargestRemainderRound#1]
Fyi, I used a variant of your library in https://github.com/Gapminder/gsheets-gm-functions/blob/master/src/lib/largestRemainderRound.ts, even added some tests based on your code comments: https://github.com/Gapminder/gsheets-gm-functions/blob/master/src/lib/largestRemainderRound.spec.ts

**Comment by ManNguyen** [comment]
glad that my tiny tweeny library is helpful :)
